name: badges_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.1
  flutter_svg: ^1.1.6
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/images/icons/
    - assets/images/badges/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham-Black
      fonts:
        - asset: assets/fonts/Gotham-Black.otf

    - family: Gotham-Book
      fonts:
        - asset: assets/fonts/Gotham-Book.otf

    - family: Gotham-Light
      fonts:
        - asset: assets/fonts/Gotham-Light.otf

    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf

    - family: Gotham-Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
